### PR TITLE
Add verification, check for no libs

### PR DESCRIPTION
**Pull request by androm3da**

### CODE REVIEW

**Comment by aleclearmind** [comment]
Hi! Thanks for the PR.

* First patch: please wrap at 79 columns.
* Second patch: why make `t` explicit, isn't it the default?
* Third patch: the verification step is a good idea, but the `if __name__ == '__main__':` is not the intended behavior. I want it to generate the wrapper transparently when you import the module, not when you run `llvm.py` as a standalone script (which you're not supposed to).

**Comment by androm3da** [comment]
Ok, I'll fix the wrapping and omit the text mode commit.

I'll take out the  "`if __name__ == '__main__':`" -- this part of the design didn't click until you explained it just now.

I'm curious about the rationale.  Why not just put this into the setup.py statically, and install it as a part of the llvmcpy package?

**Comment by aleclearmind** [comment]
The idea is that the user can have multiple installations of LLVM and can decide at run-time which one to use by letting `llvmcpy` see one or another (by putting in `PATH` the directory of the corresponding `llvm-config` program). I should make this explicit in the README.

**Comment by aleclearmind** [comment]
Can you rebase this PR and remove the unnecessary changes?

**Pull request closed without merging**
