### PR TITLE
Travis CI config

### PR DESCRIPTION
**Pull request by androm3da**
I'm hoping this PR will not see a conflict if https://github.com/revng/llvmcpy/pull/3 gets merged.

You asked for this PR to target a different branch but I don't think that would really make any sense.  It doesn't add much value unless it's on a branch where real development is occurring.  The config file is harmless if you decide to move to another CI setup.

If you prefer another branch, I think I can make it target a "travis_ci" branch.

### CODE REVIEW

**Comment by aleclearmind** [comment]
I'll consider putting it in master, my main concern is that I don't use Travis (we have our own internal CI), but I can give it a try.

Can you do the various LLVM versions thing and remove the `before_install` stuff?

**Comment by androm3da** [comment]
Ok, I misunderstood.  If there's already a CI solution in place I don't know that we need another one.  I just figured that it would be good to have precommit/PR triggered CI.  Can your solution integrate with GH?

**Comment by aleclearmind** [comment]
We have our own CI using Gitlab, but not for this particular project (yet). It might take a while before I set it up, so if you want to proceed with Travis I'm OK with that.

**Comment by aleclearmind** [comment]
Fixed in #7

**Pull request closed without merging**
